version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - medhead
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - type: volume
        source: mongodb_volume
        target: /data/db

  speciality-service:
    build: ./back/speciality-service
    container_name: speciality
    ports:
      - "9443:9443"
    expose:
      - 9443
    networks:
      - medhead
    depends_on:
      - mongodb

  hospital-service:
    build:
      context: ./back/hospital-service
      dockerfile: Dockerfile
    container_name: hospital
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - medhead
    depends_on:
      - speciality-service

  destination-service:
    build:
      context: ./back/destination-service
      dockerfile: Dockerfile
    container_name: destination
    ports:
      - "8443:8443"
    expose:
      - 8443
    networks:
      - medhead
    depends_on:
      - hospital-service
      - notification-service

  notification-service:
    build:
      context: ./back/notification-service
      dockerfile: Dockerfile
    container_name: notification
    ports:
      - "8090:8090"
    expose:
      - 8090
    networks:
      - medhead
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - medhead
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - medhead
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"

  medhead-ui:
    build:
      context: ./front/medhead-ui
      dockerfile: Dockerfile
    container_name: medhead-ui
    ports:
      - "3443:3443"
    expose:
      - 3443
    networks:
      - medhead
    depends_on:
      - destination-service
      - speciality-service

volumes:
  mongodb_volume:
    external: true

networks:
  medhead:
    driver: bridge
