spring:
  application:
    name: hospital-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      host: mongodb
      database: medhead

server:
  port: 8000
