spring:
  application:
    name: destination-service

server:
  port: 8443
#  servlet:
#    context-path: /api/v1/destination
  ssl:
    enabled: true
    key-store: classpath:localSSL.jks
    key-store-password: medhead
    key-store-type: PKCS12
    key-alias: medhead

google:
  maps:
    api-key: "AIzaSyCDE4qwwbeKMVOsBPtE4lsNjYrRohyIATQ"

