spring:
  application:
    name: destination-service

server:
  port: 8443 #8081 for http connections with redirection
  ssl:
    enabled: true
    key-store: classpath:localSSL.jks
    key-store-password: medhead
    key-store-type: PKCS12
    key-alias: medhead

app:
  cors:
    allowed-origins: https://localhost:3443,http://localhost:3000

google:
  maps:
    api-key: "AIzaSyCDE4qwwbeKMVOsBPtE4lsNjYrRohyIATQ"

