spring:
  application:
    name: speciality-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      host: mongodb
      database: medhead

server:
  port: 9443
  ssl:
    enabled: true
    key-store: classpath:localSSL.jks
    key-store-password: medhead
    key-store-type: PKCS12
    key-alias: medhead

app:
  cors:
    allowed-origins: https://medhead-ui:3443,http://medhead-ui:3000