spring:
  application:
    name: speciality-service
  data:
    mongodb:
      ## méthode 1 : docker
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      host: mongodb
      database: medhead
      ## méthode 2 : localhost
      # authentication-database: admin
      # port: 27017
      # host: localhost
      # database: medhead

server:
  port: 9443
  ssl:
    enabled: true
    key-store: classpath:medhead.p12
    key-store-password: medhead
    key-store-type: PKCS12
    key-alias: medhead
