spring:
  application:
    name: hospital-service
  data:
    mongodb:
      authentication-database: admin
      username: samir
      password: pass
      port: 27017
      host: localhost
      database: medhead

server:
  port: 8000
